name: macOS 11.0

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '34 19 * * 0'

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        mirror: http://mirrors.ocf.berkeley.edu/qt/

    - name: Get all repositories
      run: |
        git clone https://github.com/jhu-cisst/cisst-saw --recusrive ${{github.workspace}}/cisst-saw
        cd ${{github.workspace}}/cisst-saw
        git submodule foreach git checkout devel
        git submodule foreach git submodule init
        git submodule foreach git submodule update

    - name: Create cisstNetlib build directory
      run: |
        cmake -E make_directory ${{github.workspace}}/cisstNetlib-build

    - name: Build cisstNetlib
      working-directory: ${{github.workspace}}/cisstNetlib-build
      run: |
        cmake ${{github.workspace}}/cisstNetlib-source -DCMAKE_Fortran_COMPILER=gfortran-9
        cmake --build . --config Release
        sudo cmake --build . --target install

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release -C ${{github.workspace}}/.github/workflows/cmake-macos-cache.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        source cisstvars.sh
        cmake --build . --config Release
